# Generated by Django 4.2.24 on 2026-04-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woundcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='exudate',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='assessment',
            name='infection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tissue_type',
            field=models.CharField(blank=True, choices=[('granulation', 'Granulation'), ('slough', 'Slough'), ('necrosis', 'Necrosis'), ('epithelial', 'Epithelial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wound',
            name='wound_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WoundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wounds/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('wound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woundcare.wound')),
            ],
        ),
    ]
