# Generated by Django 4.2.29 on 2026-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woundcare', '0003_remove_patient_age_remove_patient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='infection',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='length',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='pain_score',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='tissue_type',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='width',
        ),
        migrations.AddField(
            model_name='assessment',
            name='aetiology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='margins',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='progression',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='surrounding_skin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tissue_epithelial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tissue_granulation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tissue_necrosis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tissue_slough',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='wound_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='exudate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
