# Generated by Django 4.2.29 on 2026-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woundcare', '0006_patient_additional_info_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
