# Generated by Django 4.2.29 on 2026-04-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woundcare', '0007_patient_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reg_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
