# Generated by Django 4.2.7 on 2026-05-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woundcare', '0010_patientaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_status',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], default='outpatient', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_ward',
            field=models.CharField(blank=True, help_text='Ward name / number when inpatient; blank when outpatient.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PatientTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('ward_to_ward', 'Ward → Ward'), ('ward_to_outpatient', 'Ward → Outpatient (Discharge)'), ('outpatient_to_ward', 'Outpatient → Ward (Admission)')], max_length=30)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='woundcare.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
    ]
